version: "1.0"
stages:
  - "pull"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "userbradley/trivy-ci"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "pull"
  get-env:
    title: "Get ENV Vars for dev"
    stage: "setup"
    image: alpine
    commands:
      - env
  build_docker:
    title: "Building Docker image"
    type: "build"
    working_directory: "trivy-ci/"
    image_name: "${{gcp_project}}/trivy-ci"
    tag: "${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
    dockerfile: "Dockerfile"
    stage: "build"